[2024-08-28T08:35:00.773+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-08-28T08:35:00.793+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_operator.insert_into_table scheduled__2024-01-30T00:00:00+00:00 [queued]>
[2024-08-28T08:35:00.800+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_operator.insert_into_table scheduled__2024-01-30T00:00:00+00:00 [queued]>
[2024-08-28T08:35:00.801+0000] {taskinstance.py:2856} INFO - Starting attempt 2 of 6
[2024-08-28T08:35:00.816+0000] {taskinstance.py:2879} INFO - Executing <Task(PostgresOperator): insert_into_table> on 2024-01-30 00:00:00+00:00
[2024-08-28T08:35:00.825+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=743) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-28T08:35:00.827+0000] {standard_task_runner.py:72} INFO - Started process 756 to run task
[2024-08-28T08:35:00.827+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_operator', 'insert_into_table', 'scheduled__2024-01-30T00:00:00+00:00', '--job-id', '51', '--raw', '--subdir', 'DAGS_FOLDER/postgres-demo.py', '--cfg-path', '/tmp/tmp1kcwsunb']
[2024-08-28T08:35:00.828+0000] {standard_task_runner.py:105} INFO - Job 51: Subtask insert_into_table
[2024-08-28T08:35:00.880+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_with_postgres_operator.insert_into_table scheduled__2024-01-30T00:00:00+00:00 [running]> on host 2d2e6ae1efc8
[2024-08-28T08:35:00.968+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='sumit kumar' AIRFLOW_CTX_DAG_ID='dag_with_postgres_operator' AIRFLOW_CTX_TASK_ID='insert_into_table' AIRFLOW_CTX_EXECUTION_DATE='2024-01-30T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-30T00:00:00+00:00'
[2024-08-28T08:35:00.969+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-08-28T08:35:00.969+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-08-28T08:35:00.970+0000] {logging_mixin.py:190} INFO - Current task name:insert_into_table state:running start_date:2024-08-28 08:35:00.793660+00:00
[2024-08-28T08:35:00.970+0000] {logging_mixin.py:190} INFO - Dag name:dag_with_postgres_operator and current dag run status:running
[2024-08-28T08:35:00.971+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-08-28T08:35:00.972+0000] {sql.py:282} INFO - Executing: 
            insert into Orders values(2,'delivered')
        
[2024-08-28T08:35:00.981+0000] {base.py:84} INFO - Retrieving connection 'postgres_local'
[2024-08-28T08:35:00.991+0000] {base.py:84} INFO - Retrieving connection 'postgres_local'
[2024-08-28T08:35:01.003+0000] {sql.py:509} INFO - Running statement: 
            insert into Orders values(2,'delivered')
        , parameters: None
[2024-08-28T08:35:01.009+0000] {taskinstance.py:3301} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 288, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 456, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 514, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "orders_pkey"
DETAIL:  Key (orderid)=(2) already exists.

[2024-08-28T08:35:01.025+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-08-28T08:35:01.025+0000] {logging_mixin.py:190} INFO - Task start:2024-08-28 08:35:00.793660+00:00 end:2024-08-28 08:35:01.024357+00:00 duration:0.230697
[2024-08-28T08:35:01.026+0000] {logging_mixin.py:190} INFO - Task:<Task(PostgresOperator): insert_into_table> dag:<DAG: dag_with_postgres_operator> dagrun:<DagRun dag_with_postgres_operator @ 2024-01-30 00:00:00+00:00: scheduled__2024-01-30T00:00:00+00:00, state:running, queued_at: 2024-08-28 08:23:05.679528+00:00. externally triggered: False>
[2024-08-28T08:35:01.026+0000] {logging_mixin.py:190} INFO - Failure caused by duplicate key value violates unique constraint "orders_pkey"
DETAIL:  Key (orderid)=(2) already exists.
[2024-08-28T08:35:01.027+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_with_postgres_operator, task_id=insert_into_table, run_id=scheduled__2024-01-30T00:00:00+00:00, execution_date=20240130T000000, start_date=20240828T083500, end_date=20240828T083501
[2024-08-28T08:35:01.046+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-08-28T08:35:01.047+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 51 for task insert_into_table (duplicate key value violates unique constraint "orders_pkey"
DETAIL:  Key (orderid)=(2) already exists.
; 756)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 2995, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3149, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3173, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 288, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 456, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 514, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "orders_pkey"
DETAIL:  Key (orderid)=(2) already exists.

[2024-08-28T08:35:01.082+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 1
[2024-08-28T08:35:01.093+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/models/baseoperator.py:1378: AirflowProviderDeprecationWarning: Call to deprecated class PostgresOperator. (Please use `***.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
  result = cls.__new__(cls)

[2024-08-28T08:35:01.109+0000] {taskinstance.py:3891} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-28T08:35:01.112+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
